spring:
  application:
    name: customer-service

server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost