server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: shopping-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086
        